sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose.dev.yml build

script:
  - docker-compose -f docker-compose.dev.yml up -d
  - docker-compose -f docker-compose.dev.yml exec db psql -U postgres -d postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - docker-compose -f docker-compose.dev.yml exec db psql -U postgres -c "CREATE DATABASE emailservice;"
  - docker-compose -f docker-compose.dev.yml exec db psql -U postgres -c "CREATE DATABASE test;"
  - docker-compose -f docker-compose.dev.yml exec nest sh -c "npm run test"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: vargas88hugo/email-service
    bucket: email-server-travis
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: email-server-travis
    key: latest.zip
    bundle_type: zip
    application: email-service-travis
    deployment_group: email-service-travis-group
    region: us-east-1
    on: *2

after_success:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
