version: '3.3'

services:
  nest:
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      SECRET: '$SECRET'
      SPARKPOST_KEY: '$SPARKPOST_KEY'
      SENDGRID_KEY: '$SENDGRID_KEY'
      PORT: 80
    depends_on:
      - 'db'

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  adminer:
    image: 'adminer:4.7'
    restart: always
    ports:
      - 8080:8080
