version: '3.3'

services:
  nest:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - 'db'

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env

  adminer:
    image: 'adminer:4.7'
    restart: always
    ports:
      - 8080:8080
